# catalogo.py

# --- CATÁLOGO DE DELITOS ---
CATALOGO_DELITOS = {
    "LESIONES": "ciento cuarenta y dos",
    "AMENAZAS": "ciento cincuenta y cuatro",
    "ROBO": "doscientos doce",
    "ROBO AGRAVADO": "doscientos trece",
    "HURTO": "doscientos siete",
    "HURTO AGRAVADO": "doscientos ocho",
    "EXACCIÓN VIOLENTA (EXTORSIÓN)": "doscientos catorce",
    "HOMICIDIO SIMPLE": "ciento veintiocho",
    "HOMICIDIO AGRAVADO": "ciento veintinueve",
    "DISPAROS DE ARMA DE FUEGO": "ciento cuarenta y siete-A",
    "POSESIÓN Y TENENCIA DE DROGAS": "treinta y cuatro de la Ley Reguladora de las Actividades Relativas a las Drogas",
    "TENENCIA, PORTACIÓN O CONDUCCIÓN ILEGAL O IRESPONSABLE DE ARMA DE FUEGO": "trescientos cuarenta y seis-B",
    "AGRUPACIONES ILÍCITAS": "doscientos cuarenta y cinco",
    "RESISTENCIA": "trescientos treinta y siete",
    "VIOLENCIA INTRAFAMILIAR": "doscientos dos-A",
    "CONDUCCIÓN PELIGROSA DE VEHÍCULOS AUTOMOTORES": "ciento cuarenta y siete-E",
    "VIOLACIÓN": "ciento cincuenta y ocho",
    "VIOLACION MENOR O INCAPAZ": "ciento cincuenta y nueve",
    "OTRAS AGRESIONES SEXUALES": "ciento sesenta",
    "AGRESION SEXUALEN MENOR O INCAPAZ": "ciento sesenta y uno",
    "VIOLACION Y AGRESION SEXUAL AGRAVADA": "ciento sesenta y dos",
    "DAÑOS": "doscientos veintiuno",
    "ESTUPRO": "ciento sesenta y tres",
    "ESTUPRO POR PREVALIMIENTO": "ciento sesenta y cuatro",
    "ACOSO SEXUAL": "ciento sesenta y cinco",
    "ACTO SEXUAL DIVERSO": "ciento sesenta y seis",
    "CORRUPCIÓN DE MENORES E INCAPACES": "ciento sesenta y siete",
    "CORRUPCIÓN AGRAVADA": "ciento sesenta y ocho",
    "INDUCCIÓN, PROMOCIÓN Y FAVORECIMIENTO DE ACTOS SEXUALES O EROTICOS": "ciento sesenta y nueve",
    "REMUNERACION POR ACTOS SEXUALES O EROTICOS": "ciento sesenta y nueve A",
    "DETERMINACIÓN A LA PROSTITUCIÓN": "ciento setenta",
    "OFERTA Y DEMANDA DE PROSTITUCION AJENA": "ciento setenta A",
    "EXHIBICIONES OBSCENAS": "ciento setenta y uno",
    "PORNOGRAFIA": "ciento setenta y dos",
    "UTILIZACIÓN DE PERSONAS MENORES DE DIECIOCHO AÑOS E INCAPACES O DEFICIENTES MENTALES EN PORNOGRAFIA": "ciento setenta y tres",
    "POSESION DE PORNOGRAFIA": "ciento setenta y tres A",
    "COHECHO ACTIVO": "trescientos treinta y cinco",
    "SOBORNO TRANSNACIONAL": "trescientos treinta y cinco A",
    "TRAFICO DE INFLUENCIAS": "trescientos treinta y seis",
    "TESTAFERRATO O CONSENTIMIENTO DE USO DE NOMBRE": "trescientos treinta y seis A",
    "AGRAVANTES ESPECIALES": "trescientos treinta y seis B",
    "ATENUANTES ESPECIALES": "trescientos treinta y seis C",
    "RESISTENCIA": "trescientos treinta y siete",
    "RESISTENCIA AGRESIVA": "trescientos treinta y siete A",
    "DESOBEDIENCIA DE PARTICULARES": "trescientos treinta y ocho",
    "DESOBEDIENCIA EN CASO DE MEDIDAS CAUTELARES O DE PROTECCIÓN": "trescientos treinta y ocho A",
    "TRÁFICO DE OBJETOS PROHIBIDOS EN CENTROS PENITENCIARIOS DE DETENCIÓN O REEDUCATIVOS": "trescientos treinta y ocho B",
    "USO DE APARATOS, COMPONENTES Y ACCESORIOS ELECTRÓNICOS Y DE TELECOMUNICACIONES, EN CENTROS PENITENCIARIOS, CENTROS DE DETENCIÓN O REEDUCATIVOS": "trescientos treinta y ocho C",
    "DESACATO": "trescientos treinta y nueve",
    "INFORMACION FALSA PARA EL PROGRAMA DE PROTECCION DE VICTIMAS Y TESTIGOS": "trescientos treinta y nueve A",
    "OTRO / INGRESAR MANUALMENTE": ""
}

# --- CATÁLOGO DE AGENTES ---
CATALOGO_AGENTES = [
    {'grado': 'SUB-INSP.', 'nombre': 'RIGOBERTO ANTONIO FIGUEROA ORELLANA', 'oni_letras': 'E-mil cuatrocientos treinta y siete', 'oni_numeros': 'E-1437'},
    {'grado': 'CABO', 'nombre': 'SAUL HUMBERTO PARADA CASTRO', 'oni_letras': 'once mil seiscientos sesenta', 'oni_numeros': '11660'},
    {'grado': 'CABO', 'nombre': 'RONMEL ANTONIO HUEZO DELGADO', 'oni_letras': 'diecinueve mil quinientos seis', 'oni_numeros': '19506'},
    {'grado': 'AGTE', 'nombre': 'RAFAEL HUMBERTO ALVAREZ PINEDA', 'oni_letras': 'veintiun mil ciento setenta y siete', 'oni_numeros': '21177'},
    {'grado': 'AGTE.', 'nombre': 'ROBERTO TOBIAS PEREZ CONCE', 'oni_letras': 'veintiseis mil quinientos noventa y tres', 'oni_numeros': '26593'},
    {'grado': 'AGTE.', 'nombre': 'ALEJANDRO HUMBERTO AGUILAR LEIVA', 'oni_letras': 'veintinueve mil novecientos ochenta y uno', 'oni_numeros': '29981'},
    {'grado': 'AGTE.', 'nombre': 'KEVIN ALEXANDER ALVARADO RAMIREZ', 'oni_letras': 'treinta y cuatro mil ciento sesenta y siete', 'oni_numeros': '34167'},
    {'grado': 'AGTE.', 'nombre': 'GABRIELA BELINDA VASQUEZ GARCÍA', 'oni_letras': 'treinta y cuatro mil seiscientos seis', 'oni_numeros': '34606'},
    {'grado': 'AGTE.', 'nombre': 'BLANCA MARISOL ALVAREZ RIVAS', 'oni_letras': 'treinta y cinco mil novecientos setenta y siete', 'oni_numeros': '35977'},
    {'grado': 'AGTE.', 'nombre': 'DANILO ARMANDO CASTANEDA RUIZ', 'oni_letras': 'treinta y seis mil doscientos quince', 'oni_numeros': '36215'},
    {'grado': 'AGTE.', 'nombre': 'ANA IRIS LOPEZ ESPINOZA', 'oni_letras': 'treinta y seis mil cuatrocientos diez', 'oni_numeros': '36410'},
    {'grado': 'AGTE.', 'nombre': 'GERARDO ENRIQUE HERNANDEZ MARAVILLA', 'oni_letras': 'treinta y seis mil seiscientos noventa y tres', 'oni_numeros': '36693'},
    {'grado': 'OTRO / MANUAL', 'nombre': 'OTRO / INGRESAR MANUALMENTE', 'oni_letras': '', 'oni_numeros': ''}
]

# --- Constante para detectar cuándo usar delito manual en modo múltiple ---
OPCION_DELITO_MANUAL = "OTRO / INGRESAR MANUALMENTE"